from app.modules.workflow.utils import sanitize_python_code


class TestBarewordJsonKeywordsAreRewritten:
    """The actual bug sanitize_python_code exists to work around: AI-generated
    templates sometimes emit JSON's null/true/false as bare Python identifiers,
    which is invalid syntax (NameError/SyntaxError) on its own."""

    def test_null_becomes_none(self):
        assert sanitize_python_code("x = null") == "x = None"

    def test_true_becomes_true_keyword(self):
        assert sanitize_python_code("x = true") == "x = True"

    def test_false_becomes_false_keyword(self):
        assert sanitize_python_code("x = false") == "x = False"

    def test_rewrites_inside_a_function_body_preserving_indentation(self):
        code = "def f(params):\n    x = null\n    y = true\n    return x\n"
        expected = "def f(params):\n    x = None\n    y = True\n    return x\n"
        assert sanitize_python_code(code) == expected


class TestStringLiteralsAreNeverRewritten:
    """DP-3: a genuine string value the user wrote must survive untouched -
    this is the exact bug a blind regex replace introduces."""

    def test_double_quoted_null_untouched(self):
        assert sanitize_python_code('x = "null"') == 'x = "null"'

    def test_double_quoted_true_untouched(self):
        assert sanitize_python_code('x = "true"') == 'x = "true"'

    def test_double_quoted_false_untouched(self):
        assert sanitize_python_code('x = "false"') == 'x = "false"'

    def test_single_quoted_untouched(self):
        assert sanitize_python_code("x = 'null'") == "x = 'null'"

    def test_string_inside_a_dict_untouched(self):
        code = 'row = {"status": "true", "value": null}'
        expected = 'row = {"status": "true", "value": None}'
        assert sanitize_python_code(code) == expected

    def test_realistic_mixed_code_only_barewords_change(self):
        code = (
            'def executable_function(params):\n'
            '    status = "true"\n'
            '    flag = null\n'
            '    label = "null"\n'
            '    return {"status": status, "flag": flag, "label": label}\n'
        )
        expected = (
            'def executable_function(params):\n'
            '    status = "true"\n'
            '    flag = None\n'
            '    label = "null"\n'
            '    return {"status": status, "flag": flag, "label": label}\n'
        )
        assert sanitize_python_code(code) == expected


class TestTrailingCommaRemoval:
    def test_removes_trailing_comma_before_closing_brace(self):
        assert sanitize_python_code('x = {"a": 1,}') == 'x = {"a": 1}'

    def test_removes_trailing_comma_before_closing_bracket(self):
        assert sanitize_python_code("x = [1, 2,]") == "x = [1, 2]"


class TestFormattingIsPreserved:
    def test_identical_code_with_nothing_to_rewrite_is_byte_for_byte_unchanged(self):
        code = (
            "def autogenerated_preprocessing_function(df):\n"
            "    # Remove duplicate rows\n"
            '    df = df.drop_duplicates(keep="first")\n'
            "    df = df.reset_index(drop=True)\n"
            "    return df\n"
        )
        assert sanitize_python_code(code) == code


class TestUnparsableCodeFallsBackUnchanged:
    def test_code_that_fails_to_tokenize_is_returned_as_is(self):
        # An unterminated string literal fails to tokenize - sanitize should
        # not raise or mangle it further; the real error surfaces from exec().
        code = 'x = "unterminated'
        assert sanitize_python_code(code) == code
