"""refactor_notifications

Revision ID: 5d4d7a65f44b
Revises: k1l2m3n4o5p6
Create Date: 2026-05-28 11:47:12.480670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d4d7a65f44b'
down_revision: Union[str, None] = 'k1l2m3n4o5p6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_type_id', sa.UUID(), nullable=False),
    sa.Column('principal_type', sa.String(length=20), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.CheckConstraint("principal_type IN ('user', 'group')", name='ck_notification_recipients_principal_type'),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_type_id', 'principal_type', 'principal_id', name='uq_notification_recipients_type_principal')
    )
    op.create_index(op.f('ix_notification_recipients_notification_type_id'), 'notification_recipients', ['notification_type_id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_principal_id'), 'notification_recipients', ['principal_id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_principal_type'), 'notification_recipients', ['principal_type'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_type_id', sa.UUID(), nullable=False),
    sa.Column('type_key', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('action_url', sa.String(length=1000), nullable=False),
    sa.Column('entity_kind', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('event_key', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_notifications_event_key')
    )
    op.create_index('ix_notifications_entity', 'notifications', ['entity_kind', 'entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_group_id'), 'notifications', ['group_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type_id'), 'notifications', ['notification_type_id'], unique=False)
    op.create_index(op.f('ix_notifications_type_key'), 'notifications', ['type_key'], unique=False)
    op.create_index('ix_notifications_type_key_created_at', 'notifications', ['type_key', 'created_at'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_user_notifications_notification_user')
    )
    op.create_index(op.f('ix_user_notifications_notification_id'), 'user_notifications', ['notification_id'], unique=False)
    op.create_index('ix_user_notifications_user_created', 'user_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_index('ix_user_notifications_user_read', 'user_notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.drop_index(op.f('ix_notification_type_recipient_users_notification_type_id'), table_name='notification_type_recipient_users')
    op.drop_index(op.f('ix_notification_type_recipient_users_user_id'), table_name='notification_type_recipient_users')
    op.drop_table('notification_type_recipient_users')
    op.drop_index(op.f('ix_user_notification_settings_notification_type_id'), table_name='user_notification_settings')
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.drop_table('user_notification_settings')
    op.drop_index(op.f('ix_notification_type_recipient_groups_group_id'), table_name='notification_type_recipient_groups')
    op.drop_index(op.f('ix_notification_type_recipient_groups_notification_type_id'), table_name='notification_type_recipient_groups')
    op.drop_table('notification_type_recipient_groups')
    op.add_column('users', sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_settings')
    op.create_table('notification_type_recipient_groups',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], name=op.f('notification_type_recipient_groups_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], name=op.f('notification_type_recipient_groups_notification_type_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_type_recipient_groups_pkey')),
    sa.UniqueConstraint('notification_type_id', 'group_id', name=op.f('uq_nt_recipient_groups_type_group'))
    )
    op.create_index(op.f('ix_notification_type_recipient_groups_notification_type_id'), 'notification_type_recipient_groups', ['notification_type_id'], unique=False)
    op.create_index(op.f('ix_notification_type_recipient_groups_group_id'), 'notification_type_recipient_groups', ['group_id'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], name=op.f('user_notification_settings_notification_type_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_notification_settings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_notification_settings_pkey')),
    sa.UniqueConstraint('user_id', 'notification_type_id', name=op.f('uq_user_notification_settings_user_type'))
    )
    op.create_index(op.f('ix_user_notification_settings_user_id'), 'user_notification_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_notification_settings_notification_type_id'), 'user_notification_settings', ['notification_type_id'], unique=False)
    op.create_table('notification_type_recipient_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_types.id'], name=op.f('notification_type_recipient_users_notification_type_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_type_recipient_users_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_type_recipient_users_pkey')),
    sa.UniqueConstraint('notification_type_id', 'user_id', name=op.f('uq_nt_recipient_users_type_user'))
    )
    op.create_index(op.f('ix_notification_type_recipient_users_user_id'), 'notification_type_recipient_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_type_recipient_users_notification_type_id'), 'notification_type_recipient_users', ['notification_type_id'], unique=False)
    op.drop_index('ix_user_notifications_user_seen', table_name='user_notifications')
    op.drop_index('ix_user_notifications_user_read', table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index('ix_user_notifications_user_created', table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_notification_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index('ix_notifications_type_key_created_at', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_group_id'), table_name='notifications')
    op.drop_index('ix_notifications_entity', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_recipients_principal_type'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_principal_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_notification_type_id'), table_name='notification_recipients')
    op.drop_table('notification_recipients')
    # ### end Alembic commands ###
