/**
 * Where the Data Preprocessing dialog's steps come from (DP-7).
 *
 * The steps are stored as structured data (`preprocessingConfig`) on the
 * node, and `pythonCode` is generated from them - it is what the backend
 * runs, but no longer the source of truth for the dialog. Parsing the code
 * back into steps is only done once, for nodes saved before
 * `preprocessingConfig` existed; their next save stores the config.
 */
import {
  BASE_PYTHON_TEMPLATE,
  PreprocessingConfig,
  generatePythonCodeFromConfig,
  parsePythonCodeToConfig,
} from "./preprocessingConfig";

export type ConfigSource =
  | "stored" // read from node.preprocessingConfig
  | "migrated" // older node: parsed once from its pythonCode
  | "empty"; // new node

export interface LoadedPreprocessingConfig {
  config: PreprocessingConfig;
  source: ConfigSource;
}

interface PreprocessingNodeConfigFields {
  pythonCode?: string;
  preprocessingConfig?: PreprocessingConfig;
}

/** A deep copy, so editing steps in the dialog never mutates the saved node data. */
export function cloneConfig(config: PreprocessingConfig): PreprocessingConfig {
  return JSON.parse(JSON.stringify(config)) as PreprocessingConfig;
}

export function loadPreprocessingConfig(
  data: PreprocessingNodeConfigFields
): LoadedPreprocessingConfig {
  if (data.preprocessingConfig && Array.isArray(data.preprocessingConfig.steps)) {
    return { config: cloneConfig(data.preprocessingConfig), source: "stored" };
  }
  if (data.pythonCode) {
    try {
      return { config: parsePythonCodeToConfig(data.pythonCode), source: "migrated" };
    } catch (error) {
      console.error("Failed to read preprocessing steps from saved code:", error);
    }
  }
  return { config: { steps: [] }, source: "empty" };
}

// The body of the generated function, which the steps own. Everything else in
// pythonCode (imports, executable_function, the user's own code) is theirs.
const AUTOGEN_FUNCTION = /def autogenerated_preprocessing_function\(df\):([\s\S]*?)(?=def |$)/;

function autogenSection(code: string): string | null {
  const match = code.match(AUTOGEN_FUNCTION);
  if (!match) return null;
  // Compare ignoring trailing whitespace per line and surrounding blank lines.
  return match[1]
    .split("\n")
    .map((line) => line.trimEnd())
    .join("\n")
    .trim();
}

/**
 * True when the code's generated function is exactly what the steps would
 * generate - i.e. nobody edited it by hand in Code mode. When false,
 * regenerating from the steps would overwrite those hand edits, so the
 * dialog asks before doing that.
 */
export function generatedSectionMatchesConfig(
  code: string,
  config: PreprocessingConfig
): boolean {
  const current = autogenSection(code);
  if (current === null) {
    // No generated function at all (fully custom code): only "matches" when
    // there are no steps that would need one.
    return config.steps.length === 0;
  }
  // The untouched template of a new node has nothing hand-written to lose.
  if (current === autogenSection(BASE_PYTHON_TEMPLATE)) return true;
  return current === autogenSection(generatePythonCodeFromConfig(config, code));
}

/** True when both codes have the same generated function (ignoring whitespace). */
export function sameGeneratedSection(a: string, b: string): boolean {
  return autogenSection(a) === autogenSection(b);
}

/**
 * Whether `code` has hand edits in its generated function that regenerating
 * from `config` would overwrite. `baselineCode` is the code as it was loaded
 * or last generated by the dialog: an older node's code, produced by an
 * earlier version of the generator, differs from today's output without
 * anyone having edited it, so only a change since the baseline counts.
 */
export function hasUnsavedHandEdits(
  code: string,
  config: PreprocessingConfig,
  baselineCode: string
): boolean {
  return !sameGeneratedSection(code, baselineCode) && !generatedSectionMatchesConfig(code, config);
}

