/**
 * Refactored preprocessing configuration system
 * Uses a step-based approach where preprocessing steps can be added dynamically
 * Each step is tracked with clear markers in the generated Python code
 */

export type PreprocessingStepType = "column_filter";

export interface PreprocessingStep {
  id: string; // Unique identifier for this step
  type: PreprocessingStepType;
  enabled: boolean;
  config: StepConfig;
}

export type StepConfig = ColumnFilterStepConfig;

export interface PreprocessingConfig {
  steps: PreprocessingStep[]; // Ordered list of preprocessing steps
}

// Column Filter Step
export interface ColumnFilterStepConfig {
  columns: ColumnFilterItem[];
}

export interface ColumnFilterItem {
  name: string;
  selected: boolean;
}

/**
 * Base template for Python preprocessing code
 */
export const BASE_PYTHON_TEMPLATE = `# Generated Python function template
from typing import Optional

# Store your result in the 'result' variable
# Import any additional libraries you need
# import json
# import requests
# import datetime
import pandas as pd

# DO NOT EDIT THIS FUNCTION
def autogenerated_preprocessing_function(df):
    # STEP_MARKER_START: Preprocessing steps will be inserted here
    # STEP_MARKER_END
    return df

def executable_function(params):
    
    # This is loaded dataframe from file path:
    df = params["df"]
    # Apply the autogenerated preprocessing code
    df = autogenerated_preprocessing_function(df)

    #Write your code here

    return df`;

/**
 * Generate Python code from preprocessing configuration
 * Uses step markers to clearly identify each preprocessing step
 */
export function generatePythonCodeFromConfig(
  config: PreprocessingConfig,
  existingCode?: string
): string {
  const codeToModify = existingCode || BASE_PYTHON_TEMPLATE;

  // Find the autogenerated_preprocessing_function
  const autogenMatch = codeToModify.match(
    /def autogenerated_preprocessing_function\(df\):([\s\S]*?)(?=def |$)/
  );

  if (!autogenMatch) {
    return codeToModify;
  }

  const autogenFunctionStart = codeToModify.indexOf(autogenMatch[0]);
  const beforeAutogen = codeToModify.substring(0, autogenFunctionStart);
  const afterAutogen = codeToModify.substring(
    autogenFunctionStart + autogenMatch[0].length
  );

  // Build function body
  const autogenBodyLines: string[] = [];
  
  // Create a copy to avoid SettingWithCopyWarning
  autogenBodyLines.push("    # Create a copy to avoid SettingWithCopyWarning");
  autogenBodyLines.push("    df = df.copy()");
  autogenBodyLines.push("");

  // Generate code for each step
  config.steps.forEach((step, index) => {
    if (!step.enabled) return;

    if (index > 0 || autogenBodyLines.length > 3) {
      autogenBodyLines.push("");
    }

    // Step marker with ID and type
    autogenBodyLines.push(`    # STEP_START:${step.id}:${step.type}`);
    
    // Add minimal step configuration as JSON comment for robust parsing
    // Only store data that's ambiguous or hard to parse from code
    try {
      const minimalConfig = extractMinimalConfig(step.type, step.config);
      if (minimalConfig && Object.keys(minimalConfig).length > 0) {
        const configJson = JSON.stringify(minimalConfig);
        autogenBodyLines.push(`    # STEP_CONFIG:${configJson}`);
      }
    } catch (e) {
      console.error("Failed to serialize step config:", e);
    }
    
    switch (step.type) {
      case "column_filter":
        generateColumnFilterCode(step.config as ColumnFilterStepConfig, autogenBodyLines);
        break;
    }
    
    autogenBodyLines.push(`    # STEP_END:${step.id}:${step.type}`);
  });

  // If no steps, add placeholder
  if (config.steps.length === 0) {
    autogenBodyLines.push("    # No preprocessing steps configured");
  }

  autogenBodyLines.push("");
  autogenBodyLines.push("    return df");

  const newAutogenFunction = `def autogenerated_preprocessing_function(df):\n${autogenBodyLines.join("\n")}\n`;
  return beforeAutogen + newAutogenFunction + afterAutogen;
}

// Extract minimal config - only data that's ambiguous when parsing from code
function extractMinimalConfig(
  stepType: PreprocessingStepType,
  config: StepConfig
): Record<string, unknown> | null {
  switch (stepType) {
    case "column_filter": {
      const colConfig = config as ColumnFilterStepConfig;
      // Only store selected columns - can parse the rest from code
      return {
        selectedColumns: colConfig.columns
          .filter((c) => c.selected)
          .map((c) => c.name),
      };
    }
    default:
      return null;
  }
}

// Restore full config from minimal config and parsed code data
function restoreConfigFromMinimal(
  stepType: PreprocessingStepType,
  minimalConfig: Record<string, unknown>,
  parsedConfig: StepConfig | null
): StepConfig | null {
  if (!parsedConfig) return null;

  switch (stepType) {
    case "column_filter": {
      const parsed = parsedConfig as ColumnFilterStepConfig;
      const minimal = minimalConfig as { selectedColumns?: string[] };
      if (minimal.selectedColumns) {
        // Merge: use selectedColumns from minimal, keep all columns from parsed
        const selectedSet = new Set(minimal.selectedColumns);
        return {
          columns: parsed.columns.map((col) => ({
            ...col,
            selected: selectedSet.has(col.name),
          })),
        };
      }
      return parsed;
    }
    default:
      return parsedConfig;
  }
}

// Code generation helpers
function generateColumnFilterCode(
  config: ColumnFilterStepConfig,
  lines: string[]
): void {
  const selectedColumns = config.columns
      .filter((col) => col.selected && col.name.trim().length > 0)
      .map((col) => `"${col.name.trim()}"`)
      .join(", ");

    if (selectedColumns) {
    lines.push("    # Filter columns");
    lines.push(`    df = df[[${selectedColumns}]]`);
  }
}

/**
 * Parse Python code to extract preprocessing configuration
 * Uses step markers to identify and parse each step
 */
export function parsePythonCodeToConfig(code: string): PreprocessingConfig {
  const config: PreprocessingConfig = { steps: [] };

  // Extract autogenerated_preprocessing_function function body
  const autogenMatch = code.match(/def autogenerated_preprocessing_function\(df\):([\s\S]*?)(?=def |$)/);
  if (!autogenMatch) {
    return config;
  }

  const codeToParse = autogenMatch[1];

  // Find all step markers
  const stepPattern = /# STEP_START:([^:]+):([^\n]+)([\s\S]*?)# STEP_END:\1:\2/g;
  let match;
  
  while ((match = stepPattern.exec(codeToParse)) !== null) {
    const stepId = match[1];
    const stepType = match[2] as PreprocessingStepType;
    const stepCode = match[3];

    let stepConfig: StepConfig | null = null;

    // First, parse from code to get base structure
    let parsedFromCode: StepConfig | null = null;
    switch (stepType) {
      case "column_filter":
        parsedFromCode = parseColumnFilterStep(stepCode);
        break;
    }

    // Then, try to merge with minimal config from comment if available
    const configCommentMatch = stepCode.match(/#\s*STEP_CONFIG:(.+?)(?=\n\s*#|$)/s);
    if (configCommentMatch) {
      try {
        const configJson = configCommentMatch[1].trim();
        const minimalConfig = JSON.parse(configJson) as Record<string, unknown>;
        // Restore full config by merging minimal config with parsed code
        stepConfig = restoreConfigFromMinimal(stepType, minimalConfig, parsedFromCode);
      } catch (e) {
        console.warn(`Failed to parse STEP_CONFIG for ${stepType}:`, e);
        // Fall back to parsed code only
        stepConfig = parsedFromCode;
      }
    } else {
      // No comment, use parsed code only
      stepConfig = parsedFromCode;
    }

    if (stepConfig) {
      config.steps.push({
        id: stepId,
        type: stepType,
        enabled: true, // If step marker exists, it's enabled
        config: stepConfig,
      });
    }
  }

  // Fallback: try to parse without markers (for backward compatibility)
  if (config.steps.length === 0) {
    // Try legacy parsing
    const legacyConfig = parseLegacyCode(code);
    if (legacyConfig.steps.length > 0) {
      return legacyConfig;
    }
  }

  return config;
}

// Step parsing helpers
function parseColumnFilterStep(code: string): ColumnFilterStepConfig | null {
  // Look for column filter pattern within step code
  const pattern = /df\s*=\s*df\[\[([^\]]+)\]\]/;
  const match = code.match(pattern);
  if (!match) return null;

        const columnNames = match[1]
          .split(",")
          .map((col) => col.trim().replace(/^["']|["']$/g, ""))
          .filter((col) => col.length > 0);

  if (columnNames.length === 0) return null;

  return {
    columns: columnNames.map((name) => ({ name, selected: true })),
  };
}


/**
 * Legacy parsing for backward compatibility
 */
function parseLegacyCode(code: string): PreprocessingConfig {
  const config: PreprocessingConfig = { steps: [] };
  // This would contain the old parsing logic as fallback
  // For now, return empty config
  return config;
}

/**
 * Create a new preprocessing step
 */
export function createPreprocessingStep(
  type: PreprocessingStepType,
  id?: string
): PreprocessingStep {
  const stepId = id || `step_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  
  const config: StepConfig = { columns: [] };

  return {
    id: stepId,
    type,
    enabled: true,
    config,
  };
}

/**
 * Get step type display name
 */
export function getStepTypeDisplayName(type: PreprocessingStepType): string {
  const names: Record<PreprocessingStepType, string> = {
    column_filter: "Column Filter",
  };
  return names[type] || type;
}

// Legacy config types for component compatibility
export interface ColumnFilterConfig {
  enabled: boolean;
  columns: ColumnFilterItem[];
}

